/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_Seq_1.h"
#include "RGB1_1.h"
#include "RGB1_1_aliases.h"
#include "RGB2_1.h"
#include "RGB2_1_aliases.h"
#include "RGB3_1.h"
#include "RGB3_1_aliases.h"
#include "Analog_1.h"
#include "Analog_1_aliases.h"
#include "BUZZER.h"
#include "BUZZER_aliases.h"
#include "HV_Request.h"
#include "HV_Request_aliases.h"
#include "Drive_Request.h"
#include "Drive_Request_aliases.h"
#include "TX_CAN0.h"
#include "TX_CAN0_aliases.h"
#include "RX_CAN0.h"
#include "RX_CAN0_aliases.h"
#include "CAN_0.h"
#include "RX_CAN1.h"
#include "RX_CAN1_aliases.h"
#include "TX_CAN1.h"
#include "TX_CAN1_aliases.h"
#include "CAN_1.h"
#include "DISP.h"
#include "DISP_aliases.h"
#include "D_RST.h"
#include "D_RST_aliases.h"
#include "D_BL.h"
#include "D_BL_aliases.h"
#include "GraphicLCDIntf.h"
#include "PWM_1.h"
#include "Clock_2.h"
#include "Analog_2.h"
#include "Analog_2_aliases.h"
#include "Digital1.h"
#include "Digital1_aliases.h"
#include "Digital2.h"
#include "Digital2_aliases.h"
#include "Digital3.h"
#include "Digital3_aliases.h"
#include "Digital4.h"
#include "Digital4_aliases.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "ADC_SAR_Seq_1_intClock.h"
#include "CAN_0_isr.h"
#include "CAN_0_HFCLK.h"
#include "CAN_1_isr.h"
#include "CAN_1_HFCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

